<!-- 
		CS 166 Project by John Sun at San Jose State University
		johnsun659@gmail.com
-->

<%@include file="include/JSP/READ_DB.jsp" %>
<%@page import="JSON.Util, java.security.*, java.math.BigInteger, java.nio.charset.StandardCharsets" %>
<%
	/**
		CS 166 Project by John Sun at San Jose State University
		john.sun@sjsu.edu
	**/
%>
<html>
	<head>
		<title>CS166 Project - Login</title>
		<link rel="stylesheet" href="css/bootstrap.min.css" >
	</head>
	
	<body>
		<div class="container">
		<%
		
			//Get user input
			String username = request.getParameter("username");
			String password = request.getParameter("password");
		
			//Hash password
			MessageDigest md = MessageDigest.getInstance("SHA-256");
			byte[] passwordBytes = password.getBytes(StandardCharsets.UTF_8); //Turn string into byte array
			byte[] digest = md.digest(passwordBytes); //Use newly generated byte array to get hash
			String hashedPassword = String.format("%032X", new BigInteger(1, digest));
					
			//Prepare SQL query
			String query = "SELECT * FROM Users WHERE username=? AND password=?;";
			
			PreparedStatement secureQuery = null;
			ResultSet rs = null;
			
			try {
				secureQuery = conn.prepareStatement(query);
				secureQuery.setString(1, username);
				secureQuery.setString(2, hashedPassword);
				rs = secureQuery.executeQuery();
			
				//Check if query returned any results
				//If there are no results, user failed to log in
				if (rs.next()) {
					
					//Create a session and create attributes for later use
					HttpSession se = request.getSession(true);
					String uiq = "SELECT * FROM Users WHERE username=?;";
					PreparedStatement prepStmt = conn.prepareStatement(uiq);
					
					//Set parameter
					prepStmt.setString(1, username);
					
					//Query database for user details
					ResultSet ui = prepStmt.executeQuery();
					ui.next(); //Move cursor to first tuple
					
					//Set attribute for user session
					se.setAttribute("username", username);
					se.setAttribute("id", ui.getInt("id"));
					se.setAttribute("userRole", ui.getInt("role"));
					se.setMaxInactiveInterval(60*10); //Set time before session is invalidated
					%>
		</div>
					<% 
					//Redirect to user protected zone
					response.sendRedirect("blog_list.jsp");
				} else {
					//Redirect to login page with error message
					out.println("Login failed. Click <a href='index.jsp'>here</a> to try again.");
				}
			} catch (SQLException ex) {
				//out.print(ex); //DEBUGGING
			}
		
			
		%>
		<script src="js/bootstrap.min.js"></script>
	</body>
</html>